# yaml-language-server: $schema=https://json.schemastore.org/github-actions.json
name: Deploy Complex

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t trungnd3/complex-client-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true trungnd3/complex-client-test npm run test
