# yaml-language-server: $schema=https://json.schemastore.org/github-actions.json
name: Deploy Complex

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build test images
        run: docker build -t trungnd3/multi-client-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true trungnd3/multi-client-test npm run test

      - name: Build multiple project images
        run: |
          docker build -t trunglinh53/multi-client ./client
          docker build -t trunglinh53/multi-nginx ./nginx
          docker build -t trunglinh53/multi-server ./server
          docker build -t trunglinh53/multi-worker ./worker

      - name: Push images to docker hub
        run: |
          docker push trunglinh53/multi-client
          docker push trunglinh53/multi-nginx
          docker push trunglinh53/multi-server
          docker push trunglinh53/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EBS
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-391898470917
          existing_bucket_path: docker-multi
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
